### ISSUE TITLE
Axes in some fonts don't respond, or have only 2 or 3 positions per axis

### ISSUE THREAD

**Issue by Lorp** [devongovett/fontkit-demo#1]
I notice that the axes in certain fonts don't offer smooth adjustment, and work only at a small number of steps.

For example, Skia.ttf offers only 3 positions on the Weight axis, and 1 on Width axis. SFNSText.ttf offers only two locations on Weight. Chunk offers 3 positions on Funk, 2 on Gunk. Note that these examples are made for GX and have rather small axis values. Skia’s Weight runs from 0.48 to 3.2, its Width from 0.61998 to 1.29999. Chunk’s Funk runs from -1 to 1, its Gunk runs from 0 to 1. Notice how the number of steps corresponds to the number of integers in those ranges. So I think there’s an issue in the demo with non-integer axis values, issues which are not apparent when the axis range is large.

Great work btw!

**Comment by Lorp** [comment]
Ah, the control seems to work fine if you add ``step="0.001"`` to the ``<input type="range">`` slider element.

**Comment by devongovett** [comment]
Ah, good point. Should be fixed now. Thanks!
