### ISSUE TITLE
Feature variations do not show right after font upload

### ISSUE THREAD

**Issue by MrBrezina** [devongovett/fontkit-demo#2]
When I upload a font with feature variations which should show on the default instance (e.g., Regular), they are not apparent at first. I need to move some sliders or change the instance in the dropdown menu for the feature variation to kick in.

**Comment by devongovett** [comment]
hmm, yeah. I guess I assumed that the defaults would be equal to the font without variations applied. can fix.

**Comment by devongovett** [comment]
Should be fixed as of 349b89ec350a7fd5649fc7ad000a591b2ddc9308.
