### ISSUE TITLE
There could be a way to activate features

### ISSUE THREAD

**Issue by MrBrezina** [devongovett/fontkit-demo#4]
I know this is just a demo, but it has already proven extremely useful for me to test variable fonts. This would be a logical extension to something more like a font tester. Also a good way to show variable fonts.

**Comment by devongovett** [comment]
yeah, that might be a cool addition.

**Comment by devongovett** [comment]
Thinking about this further, I'm struggling to come up with a good UI for this. Many features are automatically turned on by the shaper for a particular script, and additionally, features are sometimes applied at the individual glyph level rather than globally. For example, the init/medi/fina etc. features for arabic are applied contextually to different parts of a word.

So the question is which features to display, and whether it is even valid to turn off the ones turned on automatically by the shaper?

**Comment by moyogo** [comment]
People engineering fonts would be interested in turning off and on the required ones, other people would want to turn on and off the optional ones.

**Comment by MrBrezina** [comment]
My suggestion would be:
- split in two blocks: a) script shaping, b) stylistic and show only features present in particular font.
- treat all features as global even if they are not. No need for local styling for the sample text.

Even then, there will be a lot of the features, so – if aiming at font devs – you could use checkboxes with the 4-letter code (perhaps full name on rollover).

Argh. another thought. Setting a language would be cool too. Then you will have one of the most advanced type testers out there. But offering a list of all languages is probably a pain, so simple text input accepting the 3-letter ISO codes?

For Rosetta, we have done it this way, but there it needed to be/look simple. The language selection is associated with the text sample. https://www.rosettatype.com/Aisha (section tester) and another version https://www.rosettatype.com/tester . Another good one is https://klim.co.nz/retail-fonts/untitled-sans/ when you edit the text.

**Comment by devongovett** [comment]
This is now done in 4a90278a5be6b7f0ed0baff84eb35a38a91a9ea8. You can select the script and language to use (it defaults to the one detected from the text you entered), and enable/disable features. The default selected features are selected by the shaper for the selected script, but you can explicitly disable them to play around as well as select additional non-default features.

![features](https://cloud.githubusercontent.com/assets/19409/26387712/8b9d3542-4004-11e7-8a41-bf61b5ffd547.gif)
