### ISSUE TITLE
Text disappears with certain Arabic characters

### ISSUE THREAD

**Issue by khaledhosny** [devongovett/fontkit-demo#5]
I’m not sure if I should report this here or in fontkit, so please let me know where to report future rendering issues.

Inserting the Arabic character `ي` causes the text to disppear when using [Mada](https://github.com/alif-type/mada/blob/master/Mada-VF.ttf) font, and even after removing it nothing shows again until the page is reloaded.

**Comment by devongovett** [comment]
Thanks, I'll take a look later today.

**Comment by devongovett** [comment]
This was a bug where composite glyphs were not applied recursively. Fixed in https://github.com/devongovett/fontkit/issues/100.

**Comment by khaledhosny** [comment]
Thanks!
