### ISSUE TITLE
Glyph positioning seems to be broken

### ISSUE THREAD

**Issue by khaledhosny** [devongovett/fontkit-demo#6]
Testing with [Mada](https://github.com/alif-type/mada/blob/master/Mada-VF.ttf) font, marks seems to have the same position in all intances. For example here is the Black `ف` in fonkit demo:
![image](https://cloud.githubusercontent.com/assets/93914/26610782/71ea1080-45b2-11e7-947d-4e9fcff608ab.png)

and in FontView:
![image](https://cloud.githubusercontent.com/assets/93914/26610860/cae3ae80-45b2-11e7-8753-57ecb30059af.png)

**Comment by devongovett** [comment]
Added support for GPOS variation adjustments in https://github.com/devongovett/fontkit/issues/101. Updated the fontkit demo website, and it looks better.

**Comment by khaledhosny** [comment]
Thanks, looks good now.
