### ISSUE TITLE
Component transformation don’s seem to be applied

### ISSUE THREAD

**Issue by khaledhosny** [devongovett/fontkit-demo#7]
The final `ا` (e.g. `فا`) in [Mada](https://github.com/alif-type/mada/blob/master/Mada-VF.ttf) font is a composite glyphs with flipped components, but fontkit does not seems to apply the transformation:
![image](https://cloud.githubusercontent.com/assets/93914/26611541/ab22dac6-45b7-11e7-8d2f-06bc3ea788ff.png)

compared to FontView:
![image](https://cloud.githubusercontent.com/assets/93914/26611581/e84b54be-45b7-11e7-89fb-a06a7f65a46b.png)

**Comment by devongovett** [comment]
Component transforms were not previously fully implemented. Added in https://github.com/devongovett/fontkit/issues/100.

**Comment by khaledhosny** [comment]
Thanks!
